### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by lokesh-sreedhara** [oracle/oracle-database-operator#49]
oracle-database-operator keeps `CrashLoopBackOff` for a SingleInstanceDatabase runtime. 

Stack Trace:

```
21.3.0.0.0
{"reconciler group": "database.oracle.com", "reconciler kind": "SingleInstanceDatabase", "name": "maximodb", "namespace": "oracle-database-operator", "GetDatabaseVersion": "oracle-database-operator/maximodb"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1a1639e]
goroutine 1630 [running]:
github.com/oracle/oracle-database-operator/controllers/database.(*SingleInstanceDatabaseReconciler).deleteWallet(0xc000665180, 0x3, {0x224ee98, 0xc0033667b0}, {{{0xc0002b4618, 0xe}, {0xc000383678, 0x0}}})
/workspace/controllers/database/singleinstancedatabase_controller.go:1665 +0xde
github.com/oracle/oracle-database-operator/controllers/database.(*SingleInstanceDatabaseReconciler).Reconcile(0xc000665180, {0x224ee98, 0xc0033667b0}, {{{0xc0002b4618, 0x1e6bac0}, {0xc000383678, 0x30}}})
/workspace/controllers/database/singleinstancedatabase_controller.go:188 +0x877
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc000648420, {0x224ee98, 0xc003366720}, {{{0xc0002b4618, 0x1e6bac0}, {0xc000383678, 0x413c14}}})
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114 +0x26f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000648420, {0x224edf0, 0xc000a1df80}, {0x1d15660, 0xc000662960})
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311 +0x33e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000648420, {0x224edf0, 0xc000a1df80})
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2

```

**Comment by psaini79** [comment]
@lokesh-sreedhara please share the SIDB controller yaml file so that we can try the same to reproduce the issue. Also, are you using 21.3 container image available on OCR?
